title: ZirconiumOS
description: An Arch Linux Distribution for all users
url: "https://zirconiumos.github.io"
username: Zicronium OS
user_description: ZirconiumOS is a rolling-release distribution aimed at creating an easty to use and accessible desktop for all.
user_title: An Arch Linux Operating System
email: jordanwaddon98@gmail.com
github_username:  waddon1
show_downloads: true
google_analytics:
exclude: ['package.json', 'src' , 'node_modules']
theme: jekyll-theme-slate
